space_between_rrb = ""
escape_bracket = true

[[message_template]]
role = "system"
content = """
You are a linguist and specialize in dependency parsing based on Universal Dependencies."""

[[message_template]]
role = "user"
content = """
We will now perform dependency parsing on <<<LANGUAGE>>> sentence.
The input sentence and its words are as below.

input sentence:
<<<SENTENCE>>>

words:
<<<TOKEN_TSV:ORTHWS>>>

- Task 1

Output the part of speech tags for each of the above words.

- Task 2

Output the parse tree as the bracketed representation while referring to the output of Task 1.
"""

[[message_template]]
role = "assistant"
content = """
- Task 1

<<<TOKEN_TSV:POS>>>

- Task 2

<<<LINEARIZED_NO_ORTH>>>
"""
