add_whitespace = "after"

[[message_template]]
role = "system"
content = """
You are a linguist and specialize in tokenization based on Universal Dependencies."""

[[message_template]]
role = "user"
content = """
We will now perform tokenization on <<<LANGUAGE>>> sentence.
Split the input sentence into words with indexes in TSV format.

input sentence:
<<<SENTENCE>>>
"""

[[message_template]]
role = "assistant"
content = """
<<<TOKEN_TSV:INDEX_ORTHWS>>>
"""
