add_whitespace = "after"

[[message_template]]
role = "system"
content = """
You are a linguist and specialize in dependency parsing based on Universal Dependencies."""

[[message_template]]
role = "user"
content = """
We will now perform dependency parsing on <<<LANGUAGE>>> sentence.
After splitting the input sentence into words as shown below, execute following two tasks:

- Task 1

Create a TSV with three fields: word index from 1 to <<<TOKEN_NUM>>> + word + part of speech.

- Task 2

Add two fields to each row of the output of Task 1: the dependent word index + the Universal Dependencies relation label.
However, for the word that is the main predicate of the sentence, the dependent word index should be 0.

input sentence:
<<<SENTENCE>>>

words:
<<<TOKEN_TSV:ORTHWS>>>

- Task 1

<<<TOKEN_TSV:INDEX_ORTHWS_POS>>>
"""

[[message_template]]
role = "assistant"
content = """
- Task 2

<<<TOKEN_TSV:INDEX_ORTHWS_POS_HEAD_LABEL>>>
"""
