name = "en-turn1-step1"
add_whitespace = "after"

[[message_template]]
role = "system"
content = """
You are <<<LANGUAGE>>> linguist and specialize in <<<LANGUAGE>>> dependency analysis based on Universal Dependencies."""

[[message_template]]
role = "user"
content = """
We will now perform dependency parsing on <<<LANGUAGE>>> sentence.
After splitting the input sentence into words as shown below, create a TSV with five fields: word index from 1 to <<<TOKEN_NUM>>> + word + the Universal Dependencies part of speech + the dependent word index + the Universal Dependencies relation.
However, for the word that is the main predicate of the sentence, the dependent word index should be 0.

input sentence:
<<<SENTENCE>>>

words:
<<<TOKEN_TSV:ORTH>>>
"""

[[message_template]]
role = "assistant"
content = """
<<<TOKEN_TSV:INDEX_ORTH_UPOS_HEAD_LABEL>>>
"""
