add_whitespace = "after"

[[message_template]]
role = "system"
content = """
You are a linguist and specialize in tokenization based on Universal Dependencies."""

[[message_template]]
role = "user"
content = """
We will now perform tokenization and part-of-speech tagging on <<<LANGUAGE>>> sentence.
Split the input sentence into words with the word indexes from 1 in TSV format, and add the fields of part-of-speech tag and UPOS.

input sentence:
<<<SENTENCE>>>
"""

[[message_template]]
role = "assistant"
content = """
<<<TOKEN_TSV:INDEX_ORTHWS_XPOS_UPOS>>>
"""
